source 'https://github.com/CocoaPods/Specs.git'


target 'IDCOAuth2Flow-iOS', :exclusive => true do
  pod "IDCOAuth2Flow-iOS", :path => "https://github.com/wanchopeblanco/IDCOAuth2Flow-iOS.git"

  
end
